version: "3.3"

services:
  streamlit_application:
    build: .
    expose:
      - 8501
    environment:
      - db_connection_string=${db_connection_string}
    container_name: streamlit_application
    networks:
      - streamlit_network
    restart: always

networks:
  streamlit_network:
