name: deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  sync-pnl-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_DEV_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.EC2_DEV_HOST }}
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/pricing_model"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: "ubuntu"
          key: ${{ secrets.EC2_DEV_KEY }}
          script: |
            cd /home/ubuntu/pricing_model
            git stash
            git pull
            # sudo docker build --tag nginx ./nginx
            sudo docker-compose up -d
        if: always()
